// resources/js/vue/components/admin/SitemapTab.vue
<!--
  SitemapTab component.

  Tab for configuring sitemap inclusion settings including
  toggle, change frequency, and priority.

  @package    ArtisanPack_UI
  @subpackage SEO

  @since      1.1.0
-->

<script setup lang="ts">
import { Checkbox, Input, Select } from '@artisanpack-ui/vue';

import type { SeoMetaResponse } from '../../../types/seo-data';

const CHANGEFREQ_OPTIONS = [
	{ value: '', name: 'Default' },
	{ value: 'always', name: 'Always' },
	{ value: 'hourly', name: 'Hourly' },
	{ value: 'daily', name: 'Daily' },
	{ value: 'weekly', name: 'Weekly' },
	{ value: 'monthly', name: 'Monthly' },
	{ value: 'yearly', name: 'Yearly' },
	{ value: 'never', name: 'Never' },
];

defineProps<{
	data: SeoMetaResponse;
	errors?: Record<string, string[]>;
}>();

const emit = defineEmits<{
	'change': [field: string, value: unknown];
}>();

function handlePriorityChange( rawValue: string ): void {
	const trimmed = String( rawValue ).trim();

	if ( !trimmed ) {
		emit( 'change', 'sitemap_priority', null );

		return;
	}

	const parsed = parseFloat( trimmed );
	emit( 'change', 'sitemap_priority', Number.isFinite( parsed ) ? parsed : null );
}
</script>

<template>
	<div class="flex flex-col gap-4">
		<Checkbox
			label="Exclude from Sitemap"
			:model-value="data.exclude_from_sitemap"
			@update:model-value="emit( 'change', 'exclude_from_sitemap', $event )"
			hint="When checked, this page will not appear in the XML sitemap"
		/>

		<template v-if="!data.exclude_from_sitemap">
			<Select
				label="Change Frequency"
				:model-value="data.sitemap_changefreq ?? ''"
				@update:model-value="emit( 'change', 'sitemap_changefreq', $event || null )"
				:options="CHANGEFREQ_OPTIONS"
				option-value="value"
				option-label="name"
				hint="How often this page is likely to change"
				:error="errors?.sitemap_changefreq?.[0]"
			/>

			<Input
				label="Priority"
				:model-value="data.sitemap_priority ?? ''"
				@update:model-value="handlePriorityChange( String( $event ) )"
				type="number"
				:min="0"
				:max="1"
				:step="0.1"
				hint="Value between 0.0 and 1.0 (default: 0.5)"
				:error="errors?.sitemap_priority?.[0]"
			/>
		</template>
	</div>
</template>

// resources/js/react/components/admin/SitemapTab.tsx
/**
 * SitemapTab component.
 *
 * Tab for configuring sitemap inclusion settings including
 * toggle, change frequency, and priority.
 *
 * @package    ArtisanPack_UI
 * @subpackage SEO
 *
 * @since      1.1.0
 */

import React from 'react';

import { Checkbox, Input, Select } from '@artisanpack-ui/react';

import type { SeoMetaResponse } from '../../../types/seo-data';

/** Available sitemap change frequency options. */
const CHANGEFREQ_OPTIONS = [
	{ value: '', label: 'Default' },
	{ value: 'always', label: 'Always' },
	{ value: 'hourly', label: 'Hourly' },
	{ value: 'daily', label: 'Daily' },
	{ value: 'weekly', label: 'Weekly' },
	{ value: 'monthly', label: 'Monthly' },
	{ value: 'yearly', label: 'Yearly' },
	{ value: 'never', label: 'Never' },
];

/** Props for the SitemapTab component. */
export interface SitemapTabProps {
	/** Current SEO meta data. */
	data: SeoMetaResponse;
	/** Callback when a field changes. */
	onChange: ( field: string, value: unknown ) => void;
	/** Validation errors keyed by field name. */
	errors?: Record<string, string[]>;
}

/**
 * Sitemap settings editing tab.
 *
 * Provides controls for including/excluding from sitemap,
 * change frequency, and priority.
 */
export function SitemapTab( { data, onChange, errors = {} }: SitemapTabProps ): React.ReactElement {
	return (
		<div className="flex flex-col gap-4">
			<Checkbox
				label="Exclude from Sitemap"
				checked={ data.exclude_from_sitemap }
				onChange={ ( e ) => onChange( 'exclude_from_sitemap', e.target.checked ) }
				hint="When checked, this page will not appear in the XML sitemap"
			/>

			{ !data.exclude_from_sitemap && (
				<>
					<Select
						label="Change Frequency"
						value={ data.sitemap_changefreq ?? '' }
						onChange={ ( e ) => onChange( 'sitemap_changefreq', e.target.value || null ) }
						options={ CHANGEFREQ_OPTIONS }
						optionValue="value"
						optionLabel="label"
						hint="How often this page is likely to change"
						error={ errors.sitemap_changefreq?.[0] }
					/>

					<Input
						label="Priority"
						value={ data.sitemap_priority ?? '' }
						onChange={ ( e ) => {
							const trimmed = e.target.value.trim();

							if ( !trimmed ) {
								onChange( 'sitemap_priority', null );

								return;
							}

							const parsed = parseFloat( trimmed );
							onChange( 'sitemap_priority', Number.isFinite( parsed ) ? parsed : null );
						} }
						type="number"
						min={ 0 }
						max={ 1 }
						step={ 0.1 }
						hint="Value between 0.0 and 1.0 (default: 0.5)"
						error={ errors.sitemap_priority?.[0] }
					/>
				</>
			) }
		</div>
	);
}
